name: substructureML

channels:
  - conda-forge
  - pyg
  - defaults

dependencies:
  - python<=3.9
  - numpy
  - pytorch
  - pip
  - graph-tool
  - pyg::pyg
  - seaborn
  - pyg::pytorch-scatter
  - jupyter
  - seml